version: "3.7"
services:

  #Shop Application
  app:
    build:
      args:
        user: vladimir
        uid: 1000
      context: ./application/
      dockerfile: ../docker-compose/Dockerfile
    image: shop-app
    container_name: shop-app
#    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./application/:/var/www
    networks:
      - shop_network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: shop-nginx
#    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./application/:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - shop_network

  #Mysl Service
  db:
    image: mysql:8.0
    container_name: shop-db
    ports:
        - "3306:3306"
    volumes:
        - ./docker-compose/volumes/mysql:/var/lib/mysql
#    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - shop_network

#  Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: shop-elasticsearch
#    restart: unless-stopped
    environment:
      - node.name=shop01
      - cluster.name=shop-cluster
      - cluster.initial_master_nodes=shop01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - shop_elasticsearch_01:/usr/share/elasticsearch/data
    networks:
      - shop_network

volumes:
  shop_elasticsearch_01:
    driver: local

networks:
  shop_network:
    driver: bridge
