version: "3.7"
services:

  #Shop Application
  app:
    build:
      args:
        user: vladimir
        uid: 1000
      context: ./application/
      dockerfile: ../docker-compose/Dockerfile
    image: elasticusage-app
    container_name: elasticusage-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./application/:/var/www
      - ./docker-compose/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - elasticusage_network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: elasticusage-nginx
#    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./application/:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - elasticusage_network

  #Mysl Service
  db:
    image: mysql:8.0
    container_name: elasticusage-db
    ports:
        - "3306:3306"
    volumes:
        - ./docker-compose/volumes/mysql:/var/lib/mysql
#    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - elasticusage_network

#  Elasticsearch service
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    user: "1000:1000"
    container_name: elasticusage-elasticsearch
#    restart: unless-stopped
    environment:
      - node.name=elasticusage01
      - cluster.name=elasticusage-docker-cluster
      - cluster.initial_master_nodes=elasticusage01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_01_data:/usr/share/elasticsearch/data
      - ./application/elastic/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt
    networks:
      - elasticusage_network

#Kibana
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - elasticusage_network

volumes:
  es_01_data:
    driver: local

networks:
  elasticusage_network:
    driver: bridge
